spring:
  application:
    name: TestProject
  output:
    ansi:
      enabled: always
  # h2:
  #   console:
  #     enabled: true
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password: ""

 datasource:
   url: jdbc:oracle:thin:@10.100.1.188:1521:ORCL
   username: A20220100
   password: A20220100
   driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle12cDialect 